Repository polyipseity/obsidian-modules, pull requests merged in 2024-01, with the labels that each got.

#13 Test commit, please revert
  .changeset/config.json
Labels: invalid

#8 Properly detect TypeScript extensions
  .changeset/stupid-berries-poke.md
  sources/require/transpile.ts
Labels: bug

#12 Improve error message for unresolved module and loading timeout
  .changeset/twelve-pillows-search.md
  assets/locales/af/translation.json
  assets/locales/am/translation.json
  assets/locales/ar/translation.json
  assets/locales/be/translation.json
  assets/locales/bg/translation.json
  assets/locales/bn/translation.json
  assets/locales/ca/translation.json
  assets/locales/cs/translation.json
  assets/locales/da/translation.json
  assets/locales/de/translation.json
  assets/locales/el/translation.json
  assets/locales/en/translation.json
  assets/locales/eo/translation.json
  assets/locales/es/translation.json
  assets/locales/eu/translation.json
  assets/locales/fa/translation.json
  assets/locales/fi/translation.json
  assets/locales/fr/translation.json
  assets/locales/gl/translation.json
  assets/locales/he/translation.json
  assets/locales/hi/translation.json
  assets/locales/hu/translation.json
  assets/locales/id/translation.json
  assets/locales/it/translation.json
  assets/locales/ja/translation.json
  assets/locales/ko/translation.json
  assets/locales/lv/translation.json
  assets/locales/ml/translation.json
  assets/locales/ms/translation.json
  assets/locales/nl/translation.json
  assets/locales/no/translation.json
  assets/locales/oc/translation.json
  assets/locales/pl/translation.json
  assets/locales/pt-BR/translation.json
  assets/locales/pt/translation.json
  assets/locales/ro/translation.json
  assets/locales/ru/translation.json
  assets/locales/se/translation.json
  assets/locales/sk/translation.json
  assets/locales/sq/translation.json
  assets/locales/sr/translation.json
  assets/locales/ta/translation.json
  assets/locales/te/translation.json
  assets/locales/th/translation.json
  assets/locales/tr/translation.json
  assets/locales/uk/translation.json
  assets/locales/ur/translation.json
  assets/locales/zh-Hans/translation.json
  assets/locales/zh-Hant/translation.json
  sources/require/require.ts
Labels: enhancement
